[package]
name = "guessin_game"
version = "1.3.10"
author = ["Yigit GUMUS <rawns0909@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"
